   <hr>
  <footer>
    <p> <a
        href="https://blucantccode.atlassian.net/?continue=https%3A%2F%2Fblucantccode.atlassian.net%2Fwelcome%2Fsoftware%3FprojectId%3D10033&atlOrigin=eyJpIjoiYTQ3Zjk1MDA3NWE2NDIzZjkxMjU4MjNhMmQxOWZhMTAiLCJwIjoiamlyYS1zb2Z0d2FyZSJ9">Jira</a>
    </p>
    <p> <a href="https://github.com/blucantcode/Web-Tech-Project---Group-1">Github</a></p>
    <p> <a href="mailto:hello@kelp.com">Contact Us</a></p>
    <p> <a href="Web-Tech-Project---Group-1/managelogin.php">Manager Login</a><p>
  </footer>