 <div class="banner">
    <nav>
      <div class="navbg">
        <div class="navbar-text">
          <p class="menu"><a href="/Web-Tech-Project---Group-1/index.php">Home</a></p>
          <p class="menu"><a href="/Web-Tech-Project---Group-1/About.php">About</a></p>
          <p class="menu"><a href="/Web-Tech-Project---Group-1/jobspage.php">Jobs</a></p>
          <p class="menu"><a href="/Web-Tech-Project---Group-1/Apply.php">Apply</a></p>
        </div>
      </div>

      <div class="rectangle"></div>

      <div class="searchbox">
        <form action="/Web-Tech-Project---Group-1/jobspage.php" method="get">
        <input type="search" name="search" placeholder="Search...">
          <button type="submit"><span class="searchbox-icon material-symbols-outlined"> search </span></button>
        </form>
      </div>
    </nav>