 <div class="banner">
    <nav>
      <div class="navbg">
        <div class="navbar-text">
          <p class="menu"><a href="index.html">Home</a></p>
          <p class="menu"><a href="About.html">About</a></p>
          <p class="menu"><a href="jobspage.html">Jobs</a></p>
          <p class="menu"><a href="Apply.html">Apply</a></p>
        </div>
      </div>

      <div class="rectangle"></div>

      <div class="searchbox">
        <form action="/search" method="get">
          <input type="search" name="q" placeholder="Search..." aria-label="Search through site content">
          <button type="submit"><span class="searchbox-icon material-symbols-outlined"> search </span></button>
        </form>
      </div>
    </nav>